name: Roleplay
author: Fozie
main: com.mcrp.roleplay.RolePlayPlugin
version: 001
commands:
   rpdoor:
      description: The RP door command
      usage: /<command>       
    icanhasbukkit:
    - "version $1-"
   money:
      description: Main economy command
      usage: /<command>
   econ:
      description: Same as /money.
      usage: /<command>
   bal:
      description: Shows players balances, only that.
      usage: /<command>